config/routes.rb
Chat::Application.routes.draw do
  resources :rooms do
    resources :messages, only: [:index, :create]
  end

  devise_for :chatters

  root :to => 'rooms#index'

end

app/models/chatter.rb
class Chatter < ActiveRecord::Base
  has_many :messages
  has_many :rooms

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :chatter
  belongs_to :room

  validates :text, presence: true, length: { maximum: 255 }
  validates :chatter, presence: true
  validates :room, presence: true
end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :chatter
  has_many :messages, dependent: :destroy

  validates :name, presence: true, length: { maximum: 255 }
  validates :chatter, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :authenticate_chatter!

  # GET /messages
  def index
    @room = Room.find(params[:room_id])
    @messages = @room.messages
    @message = Message.new

    respond_to do |format|
      format.html # index.html.erb
      format.js do
        last = params[:last].to_i
        @new_messages = Message.where('room_id = ? AND id > ?', @room.id, last)
      end
    end
  end

  # POST /messages
  def create
    @message = Message.new(params[:message])
    @message.chatter = current_chatter

    @room = Room.find(params[:room_id])
    @message.room = @room
    @messages = @room.messages

    respond_to do |format|
      if @message.save
        format.html { redirect_to room_messages_path(@room), notice: 'Message was successfully created.' }
        format.js
      else
        format.html { render action: "index" }
      end
    end
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_filter :authenticate_chatter!

  # GET /rooms
  def index
    @rooms = Room.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /rooms/1
  def show
    @room = Room.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /rooms/new
  def new
    @room = Room.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /rooms/1/edit
  def edit
    @room = Room.find(params[:id])
  end

  # POST /rooms
  def create
    @room = Room.new(params[:room])
    @room.chatter = current_chatter

    respond_to do |format|
      if @room.save
        format.html { redirect_to rooms_path, notice: 'Room was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /rooms/1
  def update
    @room = Room.find(params[:id])

    respond_to do |format|
      if @room.update_attributes(params[:room])
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /rooms/1
  def destroy
    @room = Room.find(params[:id])
    @room.destroy

    respond_to do |format|
      format.html { redirect_to rooms_url }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def emoticons(text)
    text = text.gsub ':)', '&#x1F60A;'
    text = text.gsub /:P/i, '&#x1F60B;'
    text = text.gsub /:D/i, '&#x1F604;'
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %title Chat app
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}

    / Le HTML5 shim, for IE6-8 support of HTML5 elements
    /[if lt IE 9]
    <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar{:data => {:toggle => "collapse", :target => ".nav-collapse"} }
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "Chat", "/", :class => "brand"
          .nav-collapse
            %ul.nav
              %li.active
                %a{:href => "/"} Home
            %ul.nav.pull-right
              - if chatter_signed_in?
                %li
                  = link_to 'sign out', destroy_chatter_session_path, method: :delete
              - else
                %li
                  = link_to 'sign in', new_chatter_session_path
                %li
                  = link_to 'sign up', new_chatter_registration_path
    .container
      - flash.each do |name, msg|
        = content_tag :div, :class => "alert #{name == :error ? "alert-error" : "alert-success" }" do
          %a.close{:href => "#", :data => {:dismiss => "alert"} } ×
          = msg
      = yield
      %hr
      %footer
        %p &copy; Empower on Rails 2012

app/views/messages/_form.html.haml
= simple_form_for([@room, @message], :defaults => { :input_html => { :class => 'input-xxlarge' } }, remote: true) do |f|
  = f.error_notification

  .form-inputs
    = f.input :text

  .form-actions
    = f.button :submit, :class => "btn-primary"

app/views/messages/_message.html.haml
%tr{'data-id' => message.id}
  %td= message.chatter.email
  %td!= emoticons message.text

app/views/messages/create.js.haml
$('#room tbody').append('#{escape_javascript render @message}')

app/views/messages/edit.html.haml
.page-header
  = link_to messages_path, :class => 'btn' do
    %i.icon-list-alt
    Back
  = link_to @message, :class => 'btn btn-primary' do
    %i.icon-info-sign.icon-white
    Show
  %h1 Editing message

= render 'form'

app/views/messages/index.html.haml
.page-header
  %h1= @room.name

%table.table.table-bordered.table-striped#room{'data-id' => @room.id}
  %thead
    %tr
      %th.span2 Email
      %th.span10 Text

  %tbody
    = render @messages

= render 'form'

app/views/messages/index.js.haml
$('#room tbody').append('#{escape_javascript render @new_messages}')

app/views/messages/new.html.haml
.page-header
  = link_to messages_path, :class => 'btn' do
    %i.icon-list-alt
    Back
  %h1 New message

= render 'form'

app/views/messages/show.html.haml
.page-header
  = link_to messages_path, :class => 'btn' do
    %i.icon-list-alt
    Back
  = link_to edit_message_path(@message), :class => 'btn btn-primary' do
    %i.icon-pencil.icon-white
    Edit
  %h1 Listing messages

%dl
  %dt Text:
  %dd= @message.text

app/views/rooms/_form.html.haml
= simple_form_for(@room, :defaults => { :input_html => { :class => 'input-xxlarge' } }) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name

  .form-actions
    = f.button :submit, :class => "btn-primary"

app/views/rooms/edit.html.haml
.page-header
  = link_to rooms_path, :class => 'btn' do
    %i.icon-list-alt
    Back
  = link_to @room, :class => 'btn btn-primary' do
    %i.icon-info-sign.icon-white
    Show
  %h1 Editing room

= render 'form'

app/views/rooms/index.html.haml
.page-header
  = link_to new_room_path, :class => 'btn btn-primary' do
    %i.icon-plus.icon-white
    New Room
  %h1 Listing rooms

%table.table.table-bordered.table-striped
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @rooms.each do |room|
      %tr
        %td= room.name
        %td= link_to 'Messages', room_messages_path(room)
        %td= link_to 'Edit', edit_room_path(room)
        %td= link_to 'Destroy', room, :confirm => 'Are you sure?', :method => :delete

app/views/rooms/new.html.haml
.page-header
  = link_to rooms_path, :class => 'btn' do
    %i.icon-list-alt
    Back
  %h1 New room

= render 'form'

app/views/rooms/show.html.haml
.page-header
  = link_to rooms_path, :class => 'btn' do
    %i.icon-list-alt
    Back
  = link_to edit_room_path(@room), :class => 'btn btn-primary' do
    %i.icon-pencil.icon-white
    Edit
  %h1 Listing rooms

%dl
  %dt Name:
  %dd= @room.name
  %dt Chatter:
  %dd= @room.chatter_id